__version__ = "0.10.3"
__application_name__ = "backupjca"
__author__ = "abel"
__author_email__ = "j@abel.co"
__url__ = "https://github.com/jamesabel/backupjca"
__download_url__ = "https://s3.amazonaws.com/abel.co/s3_local_backup/s3_local_backup.exe"
__description__ = "all your AWS S3 buckets, github repos, and local files to a directory/folder"
__python_version__ = "3.7.3"
